name: Testing

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13 # Choose the version you need
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Choose the version of Node.js you need

      - name: Install dependencies
        run: npm install

      - name: migrate database
        run: npm run sync:test
        env:
          DBURL: "postgres://postgres:postgres@localhost:5432/postgres"

      - name: Run Mocha tests
        env:
          DBURL: "postgres://postgres:postgres@localhost:5432/postgres"
        run: npm test
