name: Testing

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13 # Choose the version you need
        env:
          POSTGRES_USER_TEST: postgres
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB_TEST: blog_test
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Choose the version of Node.js you need

      - name: Install dependencies
        run: npm install

      - name: Create test database
      run: |
          psql -h localhost -U postgres -d postgres -c "CREATE DATABASE blog_test"
      - name: migrate database
        env:
          POSTGRES_HOST: localhost # Use localhost since the database is running in the same container
          POSTGRES_USER_TEST: postgres
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB_TEST: blog_test
        run: npm run sync:test
      - name: Run Mocha tests
        env:
          POSTGRES_HOST: localhost # Use localhost since the database is running in the same container
          POSTGRES_USER_TEST: postgres
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB_TEST: blog_test
        run: npm test
